In [1]:
import pandas as pd

In [2]:
from first_cycling_api import Race, RaceEdition

### Races

In [31]:
amstel_2019 = RaceEdition(race_id=9, year=2021) # The race_id comes from the race page URL
amstel_2019.results().results_table.head() # A pandas DataFrame of the race results

,Pos,Rider,Team,Time,UCI,Rider_ID,Rider_Country,Team_ID
0,01,Wout van Aert,Jumbo-Visma,5:03:29,500.0,18258,BEL,21829
1,02,Tom Pidcock,INEOS Grenadiers,+ 00,400.0,65025,GBR,21826
2,03,Maximilian Schachmann,BORA-hansgrohe,+ 00,325.0,16643,GER,21805
3,04,Michael Matthews,Team BikeExchange,+ 03,275.0,2211,AUS,21821
4,05,Alejandro Valverde,Movistar Team,+ 03,225.0,38,ESP,21822

In [53]:
races = pd.DataFrame()
Race_ids = [17, 13, 23, 1, 2, 3, 12, 15, 16, 14, 6, 19, 21, 9800, 4, 7, 5, 8, 9, 11, 59, 58, 24, 47, 10, 1988, 20, 22, 1172, 53, 54, 75, 35, 40]
try:
    for i in range(2016,2022):
        try:
            for j in Race_ids:
                try:
                    Race = RaceEdition(race_id=j, year=i)
                    Race = Race.results().results_table
                    Race["Year"] = i
                    Race["Race_ID"] = j
                    races = races.append(Race)
                except: pass
        except: pass
except: pass

In [54]:
races

,Pos,Rider,Team,Time,Rider_ID,Rider_Country,Team_ID,Year,Race_ID,UCI
0,01,Vincenzo Nibali,Astana Pro Team,86:32:49,133,ITA,6413.0,2016,13,NaN
1,02,Esteban Chaves,Orica - BikeExchange,+ 52,3213,COL,6421.0,2016,13,NaN
2,03,Alejandro Valverde,Movistar Team,+ 01:17,38,ESP,6420.0,2016,13,NaN
3,04,Steven Kruijswijk,Team LottoNL-Jumbo,+ 01:50,730,NED,6425.0,2016,13,NaN
4,05,Rafal Majka,Tinkoff,+ 04:37,3991,POL,6427.0,2016,13,NaN
...,...,...,...,...,...,...,...,...,...,...
168,DNF,Nacer Bouhanni,Team Ark√©a-Samsic,NaN,2530,FRA,21864.0,2021,40,NaN
169,DNF,Jakob Egholm,Trek-Segafredo,NaN,52664,DEN,21836.0,2021,40,NaN
170,DNF,Frederik Rodenberg,Uno-X Pro Cycling Team,NaN,50933,DEN,21797.0,2021,40,NaN
171,DNF,Anders Skaarseth,Uno-X Pro Cycling Team,NaN,27232,NOR,21797.0,2021,40,NaN
172,DNF,Wout Van Elzakker,Vini Zab√π,NaN,16892,NED,21869.0,2021,40,NaN

In [55]:
races[races["UCI"].isna() == False]

,Pos,Rider,Team,Time,Rider_ID,Rider_Country,Team_ID,Year,Race_ID,UCI
0,01,Geraint Thomas,Team Sky,83:17:13,716,GBR,10086.0,2018,17,1000.0
1,02,Tom Dumoulin,Team Sunweb,+ 01:51,2324,NED,10087.0,2018,17,800.0
2,03,Chris Froome,Team Sky,+ 02:24,713,GBR,10086.0,2018,17,675.0
3,04,Primoz Roglic,Team LottoNL - Jumbo,+ 03:22,18655,SLO,10085.0,2018,17,575.0
4,05,Steven Kruijswijk,Team LottoNL - Jumbo,+ 06:08,730,NED,10085.0,2018,17,475.0
...,...,...,...,...,...,...,...,...,...,...
55,56,Jens Debusschere,B&B Hotels p/b KTM,+ 18,1966,BEL,21849.0,2021,40,1.0
56,57,Donavan Grondin,Team Ark√©a-Samsic,+ 19,76398,FRA,21864.0,2021,40,1.0
57,58,Jens Reynders,Sport Vlaanderen-Baloise,+ 19,45371,BEL,21863.0,2021,40,1.0
58,59,Jenthe Biermans,Israel Start-Up Nation,+ 19,16787,BEL,21817.0,2021,40,1.0
59,60,Ben Perry,Astana-Premier Tech,+ 19,16594,CAN,21799.0,2021,40,1.0

In [56]:
races[races["Year"] == 2017]

,Pos,Rider,Team,Time,Rider_ID,Rider_Country,Team_ID,Year,Race_ID,UCI
0,01,Chris Froome,Sky,86:20:55,713,GBR,8443.0,2017,17,NaN
1,02,Rigoberto Uran,Cannondale-Drapac,+ 54,117,COL,8434.0,2017,17,NaN
2,03,Romain Bardet,AG2R La Mondiale,+ 02:20,2275,FRA,8429.0,2017,17,NaN
3,04,Mikel Landa,Sky,+ 02:21,2278,ESP,8443.0,2017,17,NaN
4,05,Fabio Aru,Astana,+ 03:05,10303,ITA,8430.0,2017,17,NaN
...,...,...,...,...,...,...,...,...,...,...
183,DNF,Robin Stenuit,Wanty-Groupe Gobert,NaN,8043,BEL,8467.0,2017,40,NaN
184,DNF,Roy Jans,WB-Veranclassic-Aqua Protect,NaN,7657,BEL,8564.0,2017,40,NaN
185,DNF,Jakub Mareczko,Wilier Triestina-Selle Italia,NaN,28738,ITA,8468.0,2017,40,NaN
186,DNF,Jacopo Mosca,Wilier Triestina-Selle Italia,NaN,20397,ITA,8468.0,2017,40,NaN
187,DNF,Filippo Pozzato,Wilier Triestina-Selle Italia,NaN,67,ITA,8468.0,2017,40,NaN

In [57]:
races.to_csv('Races_WITHindex.csv')

In [58]:
races.to_csv('Races_WITHOUTindex.csv', index=False)

### Ranking???